// actionTypes.js
export const SCHEDULE_MENSTRUATION_NOTIFICATIONS = 'SCHEDULE_MENSTRUATION_NOTIFICATIONS';
export const SCHEDULE_OVULATION_NOTIFICATIONS = 'SCHEDULE_OVULATION_NOTIFICATIONS';
export const SCHEDULE_PILL_NOTIFICATIONS = 'SCHEDULE_PILL_NOTIFICATIONS';
